### ISSUE TITLE
BasicCompletesTest fails, sometimes

### ISSUE THREAD

**Issue by zpbappi** [vlingo-net/vlingo-net-common#18]
`BasicCompletesTest.TestTimeoutBeforeOutcome()` test occasionally fails. My guess is, it is a Thread related issue. It only fails when we run all the tests in parallel. We may need to try running them in parallel multiple times to see it fail. That makes it difficult to debug. Here is a link to a recent failure: https://ci.appveyor.com/project/VlingoNetOwner/vlingo-net-common/builds/20983605/tests

**Comment by zpbappi** [comment]
Just happened again today few times. Here is the latest log of such failure: https://ci.appveyor.com/project/VlingoNetOwner/vlingo-net-common/builds/24276976/tests

**Comment by tjaskula** [comment]
This will be fixed in #43

**Comment by tjaskula** [comment]
Fixed in #43
