### ISSUE TITLE
The resulting Task in AsyncMessageQueue should be cancelled

### ISSUE THREAD

**Issue by tjaskula** [vlingo-net/vlingo-net-common#33]
The resulting `Task` should be awaited when closing the mailbox and any catches exceptions should be logged.

https://github.com/vlingo-net/vlingo-net-common/blob/a551e337108702c54aed97346f14a6bfc207950f/src/Vlingo.Common/Message/AsyncMessageQueue.cs#L43

**Comment by zpbappi** [comment]
@tjaskula good catch. However, it is in the constructor. We may need to change the implementation a little to make it work. e.g., using a background thread or worker.

**Comment by tjaskula** [comment]
@zpbappi We can take a reference to the task and keep it in the private field. Then when the queue is disposed we can cancel the task

**Comment by vany0114** [comment]
I was taking a look at this guy, but it seems it is already fixed :)

**Comment by tjaskula** [comment]
Fixed in #34
